### ISSUE TITLE
UnicodeEncodeError ZKM on disassembling

### ISSUE THREAD

**Issue by i0xHeX** [Storyyeller/Krakatau#134] opened 2018-02-13 15:19 UTC
Python 3.7.0a2
Krakatau latest zip from here.
Tried to disassemble zkm 9:
https://hastebin.com/numaluhemu.sql

It's seems problem with default Windows encoding. I googled. but found nothing useful how to fix this.
Also tried to change `151` line `script_util.py` to `with open(out, mode, encoding='utf-8')`. Disassembling good but Assembling failing with and without `encoding='utf-8'`.

**Comment by Storyyeller** [comment] 2018-02-13 15:22
Does this happen only on Windows? Also, could you post the file you were trying to disassemble?

**Comment by i0xHeX** [comment] 2018-02-13 15:27
I didn't tried on other platforms, but on my google searching seems unix platforms do not have similar issues.
Link to file: https://www.dropbox.com/s/8l4ucu1st615ygn/hb.class?dl=0

**Comment by i0xHeX** [comment] 2018-02-13 16:15
Default encoding is utf8:
_>>> import sys
>>> sys.getdefaultencoding()
'utf-8'_

**Comment by i0xHeX** [comment] 2018-02-13 16:16
Default encoding is utf8:
```
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'
```

**Comment by i0xHeX** [comment] 2018-02-13 16:29
This fixed my issue:
https://hastebin.com/enohupijas.pas

**Comment by Storyyeller** [comment] 2018-02-14 05:49
Thanks for investigating this. I'll hopefully get to it over the weekend.

**Comment by Storyyeller** [comment] 2018-02-19 20:40
Could you repost the file please? The link isn't working for me.

**Comment by i0xHeX** [comment] 2018-02-19 20:53
https://ghostbin.com/paste/urx5r

**Comment by Storyyeller** [comment] 2018-02-19 21:35
No, I mean the classfile that caused the error.

**Comment by i0xHeX** [comment] 2018-02-20 05:42
https://www.dropbox.com/s/f3lrmwgrjhqoli3/hb%26gl.zip?dl=0

**Comment by i0xHeX** [comment] 2018-02-23 11:44
How are things?

**Comment by Storyyeller** [comment] 2018-02-23 14:57
Sorry, I'll try to get to it over the weekend.

**Comment by Storyyeller** [comment] 2018-02-24 19:15
I tried disassembling the file you provided on my old Windows machine, but it disassembled without errors.

**Comment by Storyyeller** [comment] 2018-02-24 19:27
Ok, I went ahead and pushed a fix for the issue I noticed. I can't reproduce the original error, so I'll close this for now, but if you find a way to reliably reproduce it, feel free to reply.

**Closed by Storyyeller** 2018-02-24 19:27 UTC
